// auth reducer
export const LOGIN_WITH_GOOGLE = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const LOGOUT = 'LOGOUT'
export const AUTHORIZE = 'AUTHORIZE'
export const UPDATE_LOGIN_ERRORS = 'UPDATE_LOGIN_ERRORS'
// library reducer
export const SORT_USER_BOOKS = 'SORT_USER_BOOKS'
export const FILTER_USER_BOOKS = 'FILTER_USER_BOOKS'
export const SET_USER_BOOKS = 'SET_USER_BOOKS'
export const SET_SELECTED_LIBRARY_BOOK = 'SET_SELECTED_LIBRARY_BOOK'
// currentChapter reducer
export const START_READER = 'START_READER'
export const END_READER = 'END_READER'
export const SET_CURRENT_CHAPTER = 'SET_CURRENT_CHAPTER'
export const SET_PREVIOUS_CHAPTER = 'SET_CURRENT_CHAPTER'
export const SET_NEXT_CHAPTER = 'SET_CURRENT_CHAPTER'
// comments reducer
export const GET_COMMENTS_FOR_CURRENT_CHAPTER = 'GET_COMMENTS_FOR_CURRENT_CHAPTER'
