// auth reducer
export const LOGIN_WITH_GOOGLE = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const LOGOUT = 'LOGOUT'
export const AUTHORIZE = 'AUTHORIZE'
export const UPDATE_LOGIN_ERRORS = 'UPDATE_LOGIN_ERRORS'


// library reducer
export const SET_SORT_USER_BOOKS_VALUE = 'SET_SORT_USER_BOOKS_VALUE'
export const SET_FILTER_USER_BOOKS_VALUE = 'SET_FILTER_USER_BOOKS_VALUE'
export const SEARCH_AND_FILTER_LIBRARY = 'SEARCH_AND_FILTER_LIBRARY'
export const SET_USER_LIBRARY = 'SET_USER_LIBRARY'
export const SET_SELECTED_LIBRARY_BOOK = 'SET_SELECTED_LIBRARY_BOOK'
export const UPDATE_LIBRARY_RETRIEVAL_ERRORS = 'UPDATE_LIBRARY_RETRIEVAL_ERRORS'
export const CLEAR_LIBRARY = 'CLEAR_LIBRARY'
// currentChapter reducer
export const START_READER = 'START_READER'
export const END_READER = 'END_READER'
export const SET_CURRENT_CHAPTER = 'SET_CURRENT_CHAPTER'
export const SET_PREVIOUS_CHAPTER = 'SET_PREVIOUS_CHAPTER'
export const SET_NEXT_CHAPTER = 'SET_NEXT_CHAPTER'
export const UPDATE_CHAPTER_LOCATION = 'UPDATE_CHAPTER_LOCATION'
export const CLEAR_CURRENT_CHAPTER = 'CLEAR_CURRENT_CHAPTER'
export const NEXT_CHAPTER_TRANSITION = 'NEXT_CHAPTER_TRANSITION'
// comments reducer
export const SET_COMMENTS = 'SET_COMMENTS'
